- name: Create Redis directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: "0750"
  loop:
    - "{{ redis_data_dir }}"
    - "{{ redis_log_dir }}"

- name: Deploy redis.conf
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    mode: "0640"
  notify: restart redis
