- name: Enable RPM Fusion free
  dnf:
    name: https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Enable RPM Fusion nonfree
  dnf:
    name: https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-9.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Install FFmpeg
  dnf:
    name: ffmpeg
    state: present
    allowerasing: true

