- name: Create pgBackRest directories
  file:
    path: "{{ pgbackrest_repo_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: "0750"

- name: Deploy pgBackRest config
  template:
    src: pgbackrest.conf.j2
    dest: /etc/pgbackrest.conf
    owner: root
    group: root
    mode: "0644"
