- name: Install pgBackRest
  import_tasks: install.yml

- name: Configure pgBackRest
  import_tasks: config.yml

- name: Create pgBackRest stanza
  import_tasks: stanza.yml

# ⚠️ 복구는 명시적으로 허용했을 때만
- name: Restore PostgreSQL from pgBackRest
  import_tasks: restore.yml
  when: dr_restore | bool
