ai_base_dir: /opt/ai
ai_jobs_dir: /opt/ai/jobs
ai_output_dir: /opt/ai/output

redis_host: 10.1.1.10
redis_port: 6379
redis_password: ""

ai_audio_retention_days: 3
ai_log_retention_days: 14
ai_status_retention_days: 14

