# Redis user / group
redis_user: redis
redis_group: redis

# Redis network
redis_bind_address: 0.0.0.0
redis_port: 6379

# Paths
redis_conf_path: /etc/redis/redis.conf
redis_data_dir: /var/lib/redis
redis_log_dir: /var/log/redis
redis_logfile: /var/log/redis/redis.log

# Persistence (RDB only – Job Queue 보호)
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"

redis_appendonly: "no"

# Memory
redis_maxmemory: 2gb
redis_maxmemory_policy: noeviction

# Network tuning
redis_tcp_backlog: 511
redis_timeout: 0
redis_tcp_keepalive: 300

# Logging
redis_loglevel: notice

redis_requirepass: ""
