# Redis 기본 설정
redis_bind_address: 0.0.0.0
redis_port: 6379

# 메모리 정책
redis_maxmemory: 2gb
redis_maxmemory_policy: noeviction

# Persistence (Job Queue 보호)
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"

redis_appendonly: "no"

# 보안
redis_requirepass: "{{ vault_redis_password }}"

# 성능/안정성
redis_tcp_backlog: 511
redis_timeout: 0
redis_tcp_keepalive: 300

# 로그
redis_loglevel: notice
redis_logfile: /var/log/redis/redis.log
